chiquitoArray = [
"fistro",
"torpedo",
"pecador",
"sexuarl",
"por la gloria de mi madre",
"diodeno",
"condemor",
"jarl",
"ese que llega",
"pupita",
"la caidita",
"te voy a borrar el cerito",
"al ataquerl",
"a wan",
"a peich",
"a gramenawer",
"no puedor",
"hasta luego Lucas",
"mamaar",
"apetecan",
"caballo blanco caballo negroorl",
"ese pedazo de",
"benemeritaar",
"te va a hasé pupitaa",
"de la pradera",
"ese hombree",
"quietooor",
"qué dise usteer",
"no te digo trigo por no llamarte Rodrigor",
"está la cosa muy malar",
"tiene musho peligro",
"ahorarr",
"diodenoo",
"amatomaa",
"me cago en tus muelas",
"llevame al sircoo",
"papaar papaar",
"se calle ustée",
"va usté muy cargadoo"]